# I failed to build it inside the docker.
# So build local first: cargo build --bin userspace --release --target=x86_64-unknown-linux-musl

FROM alpine:latest

ENV LISTEN=""
ENV TARGET=""
ENV PROXY=""
ENV USERNAME=""
ENV PASSWORD=""

COPY ./entrypoint.sh /
COPY ./target/x86_64-unknown-linux-musl/release/userspace /usr/local/bin/socks5-forwarder
RUN chmod +x /entrypoint.sh && apk add --no-cache ca-certificates
ENTRYPOINT ["/entrypoint.sh"]
